Fix a warning when there are only enums, no messages. (#370)
Previously we got:

```
...../build/enum_test/autogen/Proto/EnumOnly.hs:72:1: error: [-Wunused-top-binds, -Werror=unused-top-binds]
    Defined but not used: ‘packedFileDescriptor’
   |
72 | packedFileDescriptor
   | ^^^^^^^^^^^^^^^^^^^^
```

The check for whether the file had any messages was incorrect, since it didn't account for enums which are tracked in the same map.